[package]
name = "integrate-and-fire"
version = "0.1.0"
authors = ["doraneko94 <shuntaro941@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.31"